config/routes.rb
Rails.application.routes.draw do
  resources :grower_fields
  resources :growers
  resources :fields
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/field.rb
class Field < ApplicationRecord
    validates :name, :area, :area_unit, presence: true
    validates :area, numericality: { greater_than_or_equal_to: 0.01 }, :allow_blank => true
    validates :area_unit, inclusion: { in: %w(hectares acres) }, :allow_blank => true
    has_many :grower_fields
    has_many :growers, :through => :grower_fields
end

app/models/grower.rb
class Grower < ApplicationRecord
    validates :phone_number, phone: true
    validates :first_name, :last_name, :email, presence: true
    validates :email, uniqueness: true
    has_many :grower_fields
    has_many :fields, :through => :grower_fields
end

app/models/grower_field.rb
class GrowerField < ApplicationRecord
    belongs_to :grower
    belongs_to :field
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :area, :area_unit)
    end
end

app/controllers/grower_fields_controller.rb
class GrowerFieldsController < ApplicationController
  before_action :set_grower_field, only: [:show, :edit, :update, :destroy]

  # GET /grower_fields
  # GET /grower_fields.json
  def index
    @grower_fields = GrowerField.all
  end

  # GET /grower_fields/1
  # GET /grower_fields/1.json
  def show
  end

  # GET /grower_fields/new
  def new
    @grower_field = GrowerField.new
  end

  # GET /grower_fields/1/edit
  def edit
  end

  # POST /grower_fields
  # POST /grower_fields.json
  def create
    @grower_field = GrowerField.new(grower_field_params)

    respond_to do |format|
      if @grower_field.save
        format.html { redirect_to @grower_field, notice: 'Grower field was successfully created.' }
        format.json { render :show, status: :created, location: @grower_field }
      else
        format.html { render :new }
        format.json { render json: @grower_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grower_fields/1
  # PATCH/PUT /grower_fields/1.json
  def update
    respond_to do |format|
      if @grower_field.update(grower_field_params)
        format.html { redirect_to @grower_field, notice: 'Grower field was successfully updated.' }
        format.json { render :show, status: :ok, location: @grower_field }
      else
        format.html { render :edit }
        format.json { render json: @grower_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grower_fields/1
  # DELETE /grower_fields/1.json
  def destroy
    @grower_field.destroy
    respond_to do |format|
      format.html { redirect_to grower_fields_url, notice: 'Grower field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grower_field
      @grower_field = GrowerField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grower_field_params
      params.require(:grower_field).permit(:grower_id, :field_id, :assign_date)
    end
end

app/controllers/growers_controller.rb
class GrowersController < ApplicationController
  before_action :set_grower, only: [:show, :edit, :update, :destroy]

  # GET /growers
  # GET /growers.json
  def index
    @growers = Grower.all
  end

  # GET /growers/1
  # GET /growers/1.json
  def show
  end

  # GET /growers/new
  def new
    @grower = Grower.new
  end

  # GET /growers/1/edit
  def edit
  end

  # POST /growers
  # POST /growers.json
  def create
    @grower = Grower.new(grower_params)

    respond_to do |format|
      if @grower.save
        format.html { redirect_to @grower, notice: 'Grower was successfully created.' }
        format.json { render :show, status: :created, location: @grower }
      else
        format.html { render :new }
        format.json { render json: @grower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /growers/1
  # PATCH/PUT /growers/1.json
  def update
    respond_to do |format|
      if @grower.update(grower_params)
        format.html { redirect_to @grower, notice: 'Grower was successfully updated.' }
        format.json { render :show, status: :ok, location: @grower }
      else
        format.html { render :edit }
        format.json { render json: @grower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /growers/1
  # DELETE /growers/1.json
  def destroy
    @grower.destroy
    respond_to do |format|
      format.html { redirect_to growers_url, notice: 'Grower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grower
      @grower = Grower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grower_params
      params.require(:grower).permit(:first_name, :last_name, :phone_number, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/grower_fields_helper.rb
module GrowerFieldsHelper
end

app/helpers/growers_helper.rb
module GrowersHelper
end

app/views/fields/_form.html.erb
<%= form_with(model: field, local: true) do |form| %>
  <% if field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :field_name %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.text_field :area, id: :field_area %>
  </div>

  <div class="field">
    <%= form.label :area_unit %>
    <%= form.text_field :area_unit, id: :field_area_unit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Area</th>
      <th>Area unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= field.area %></td>
        <td><%= field.area_unit %></td>
        <td><%= link_to 'Show', field %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @field.area %>
</p>

<p>
  <strong>Area unit:</strong>
  <%= @field.area_unit %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/grower_fields/_form.html.erb
<%= form_with(model: grower_field, local: true) do |form| %>
  <% if grower_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grower_field.errors.count, "error") %> prohibited this grower_field from being saved:</h2>

      <ul>
      <% grower_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :grower_id %>
    <%= form.number_field :grower_id, id: :grower_field_grower_id %>
  </div>

  <div class="field">
    <%= form.label :field_id %>
    <%= form.number_field :field_id, id: :grower_field_field_id %>
  </div>

  <div class="field">
    <%= form.label :assign_date %>
    <%= form.date_select :assign_date, id: :grower_field_assign_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grower_fields/edit.html.erb
<h1>Editing Grower Field</h1>

<%= render 'form', grower_field: @grower_field %>

<%= link_to 'Show', @grower_field %> |
<%= link_to 'Back', grower_fields_path %>

app/views/grower_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grower Fields</h1>

<table>
  <thead>
    <tr>
      <th>Grower</th>
      <th>Field</th>
      <th>Assign date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grower_fields.each do |grower_field| %>
      <tr>
        <td><%= grower_field.grower_id %></td>
        <td><%= grower_field.field_id %></td>
        <td><%= grower_field.assign_date %></td>
        <td><%= link_to 'Show', grower_field %></td>
        <td><%= link_to 'Edit', edit_grower_field_path(grower_field) %></td>
        <td><%= link_to 'Destroy', grower_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grower Field', new_grower_field_path %>

app/views/grower_fields/new.html.erb
<h1>New Grower Field</h1>

<%= render 'form', grower_field: @grower_field %>

<%= link_to 'Back', grower_fields_path %>

app/views/grower_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grower:</strong>
  <%= @grower_field.grower_id %>
</p>

<p>
  <strong>Field:</strong>
  <%= @grower_field.field_id %>
</p>

<p>
  <strong>Assign date:</strong>
  <%= @grower_field.assign_date %>
</p>

<%= link_to 'Edit', edit_grower_field_path(@grower_field) %> |
<%= link_to 'Back', grower_fields_path %>

app/views/growers/_form.html.erb
<%= form_with(model: grower, local: true) do |form| %>
  <% if grower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grower.errors.count, "error") %> prohibited this grower from being saved:</h2>

      <ul>
      <% grower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :grower_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :grower_last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, id: :grower_phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :grower_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/growers/edit.html.erb
<h1>Editing Grower</h1>

<%= render 'form', grower: @grower %>

<%= link_to 'Show', @grower %> |
<%= link_to 'Back', growers_path %>

app/views/growers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Growers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @growers.each do |grower| %>
      <tr>
        <td><%= grower.first_name %></td>
        <td><%= grower.last_name %></td>
        <td><%= grower.phone_number %></td>
        <td><%= grower.email %></td>
        <td><%= link_to 'Show', grower %></td>
        <td><%= link_to 'Edit', edit_grower_path(grower) %></td>
        <td><%= link_to 'Destroy', grower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grower', new_grower_path %>

app/views/growers/new.html.erb
<h1>New Grower</h1>

<%= render 'form', grower: @grower %>

<%= link_to 'Back', growers_path %>

app/views/growers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @grower.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @grower.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @grower.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @grower.email %>
</p>

<%= link_to 'Edit', edit_grower_path(@grower) %> |
<%= link_to 'Back', growers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>